### ISSUE TITLE
Failed to load the colorful-json package

### ISSUE THREAD

**Issue by s-ogawa-mediba** [smockle/colorful-json#2] opened 2015-04-30 08:23 UTC
[Enter steps to reproduce below:]
1. setting > install
2. type `colorful-json` in search box > press enter
3. click install button

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [colorful-json](https://github.com/smockle/colorful-json) package, v0.1.0
### Stack Trace

Failed to load the colorful-json package

```
At 'colors.less' wasn't found in /Users/s-ogawa/.atom/packages/colorful-json/styles/colorful-json.less:1:0

LessError: 'colors.less' wasn't found
  at /Users/s-ogawa/.atom/packages/colorful-json/styles/colorful-json.less:1:0
```
### Commands

```
     -1:00.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:59.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:59.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:58.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:55.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:53.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:53.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:51.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.5.0 core:save (atom-text-editor.editor.is-focused)
 33x -0:47.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:45.7.0 core:save (atom-text-editor.editor.is-focused)
  6x -0:17.5.0 core:backspace (atom-text-editor.editor.mini)
     -0:13.3.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/s-ogawa/"
  }
}
```
### Installed Packages

``` coffee
# User
colorful-json, v0.1.0
file-icons, v1.5.4
jshint, v1.3.5
localization, v1.16.1
minimap, v4.7.6
monokai, v0.14.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by ArthurZ** [comment] 2015-05-05 13:29
I have the same issue.
Stack trace
LessError: 'colors.less' wasn't found
  at C:\Users\ArthurZ.atom\packages\colorful-json\styles\colorful-json.less:1:0

**Comment by keiththecomputerguy** [comment] 2015-05-11 00:48
Same issue here

**Comment by smockle** [comment] 2015-05-22 08:31
@s-ogawa-mediba Thank you for the detailed report! I’m very sorry it’s taken me so long to reply; I’d turned off automatic watching, not realizing that setting would affect my own repos.

This looks like a duplicate of #1, so I’ll close this issue and continue discussion in that one. Feel free to reopen if you feel this issue is separate.

@s-ogawa-mediba @ArthurZ @keithgordon Thank you all again for your feedback, and for your patience!

**Closed as completed by smockle** 2015-05-22 08:31 UTC
Labels: duplicate
