### ISSUE TITLE
Failed to reload the colorful-json package stylesheets

### ISSUE THREAD

**Issue by madrus** [smockle/colorful-json#3] opened 2015-05-09 15:58 UTC
[Enter steps to reproduce below:]
1. In the Settings, I have chosen Atom Dark theme instead of One Dark theme.
2. Bum!

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [colorful-json](https://github.com/smockle/colorful-json) package, v0.1.0
### Stack Trace

Failed to reload the colorful-json package stylesheets

```
At 'colors.less' wasn't found in C:\Users\Andre\.atom\packages\colorful-json\styles\colorful-json.less:1:0

LessError: 'colors.less' wasn't found
  at C:\Users\Andre\.atom\packages\colorful-json\styles\colorful-json.less:1:0
```
### Commands

```
  2x -9:56 core:move-down (atom-text-editor.editor.is-focused)
  2x -9:54.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -9:52.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -9:51.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -9:50.3.0 core:cut (atom-text-editor.editor.is-focused)
  3x -9:49.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:40.7.0 core:paste (atom-text-editor.editor.is-focused)
     -9:36.7.0 core:save (atom-text-editor.editor.is-focused)
     -9:18.7.0 open-on-github:repository (atom-text-editor.editor.is-focused)
     -5:34.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
angularjs-snippets, v0.10.2
angularjs-styleguide-snippets, v0.7.0
atom-beautify, v0.27.1
atom-color-highlight, v3.0.9
coffee-lint, v0.7.3
coffee-navigator, v0.0.16
color-picker, v1.7.0
colorful-json, v0.1.0
file-icons, v1.5.5
Handlebars, v1.0.1
jshint, v1.3.6
language-emberscript, v0.1.0
less-autocompile, v1.0.0
linter, v0.12.2
linter-csslint, v0.0.12
linter-jscs, v1.11.0
linter-jshint, v0.1.4
linter-jsxhint, v0.1.1
linter-scss-lint, v0.0.14
minimap, v4.8.0
react, v0.11.8
remember-session, v0.5.1

# Dev
No dev packages
```

**Comment by smockle** [comment] 2015-05-22 08:35
@madrus Thank you so much for the detailed report! I’m very sorry for the delayed response—I’d disabled automatic watching, not realizing it would cause me to miss issues in my own repos.

This appears to be a duplicate of #1. I’ll go ahead and close this issue, and we can continue discussion there. If you believe this is a separate issue, please feel free to reopen it.

Again, many thanks for reporting, and for your patience!

**Closed as completed by smockle** 2015-05-22 08:35 UTC
Labels: duplicate
